spring.application.name=ex0708_step3

server.port=8185

#DB
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=postgres
spring.datasource.password=1234

#mybatis 설정config파일
mybatis.config-location=classpath:mybatis/mybatis-config.xml
#mybatis 매퍼mapper파일 _쿼리문작성
mybatis.mapper-locations=classpath:mybatis/mapper/*.xml