-- 강사 테이블 생성
CREATE TABLE golf_teacher(
	-- 100부터 시작해서 100씩 증가
	teacher_code int GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 100) PRIMARY KEY,
	teacher_name varchar(15),
	class_name varchar(20),
	class_price int,
	teacher_regist_date date
	);

-- 회원정보 테이블 생성
CREATE TABLE golf_member(
	-- 10000부터 시작해서 1씩 증가
	c_no int GENERATED BY DEFAULT AS IDENTITY (START WITH 10001 INCREMENT BY 1) PRIMARY KEY,
	c_name varchar(15),
	phone varchar(11),
	address varchar(50),
	grade varchar(5)
	);

-- 수강정보 테이블 생성
CREATE TABLE golf_class(
    regist_month varchar(6) NOT NULL,
    c_no int NOT NULL,
    class_area varchar(15),
    tuition int,
    teacher_code int,
    -- 복합 기본키는 테이블 정의 하단에 일괄 선언
    PRIMARY KEY (regist_month, c_no),
    -- 무결성을 위한 FK 제약조건
    FOREIGN KEY (c_no) REFERENCES golf_member(c_no),
    FOREIGN KEY (teacher_code) REFERENCES golf_teacher(teacher_code)
	);


